# Welcome to Jekyll!
#

# Site settings
title: Blue Canary
description: Belgian Cyber Security Firm
owner: Blue Canary # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: montegnies.dennis@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://bluecanary.be" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/zerodaydotio
  github: https://github.com/bluecanarybe/
  linkedin-square: https://linkedin.com/in/dennis-m-42b58926
  email: mailto:dennis@bluecanary.be
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
#sass:
#  style: compressed
