# Welcome to Jekyll!
#

# Site settings
title: Blue Canary
description: Belgian Cyber Security Firm
owner: Blue Canary # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: montegnies.dennis@gmail.com
baseurl: "/BlueCanary" # the subpath of your site, e.g. /blog
url: "https://faun88.github.io/BlueCanary" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/zerodaydotio
  github: https://github.com/faun88
  linkedin-square: https://linkedin.com/in/dennis-m-42b58926
  email: mailto:montegnies.dennis@gmail.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
